version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: ecomanalyser_db
    environment:
      POSTGRES_DB: ecomanalyser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    container_name: ecomanalyser_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecomanalyser
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db_data:

