spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomanalyser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ecomanalyser.service.ExcelImportService: DEBUG
    com.ecomanalyser: DEBUG

